In [2]:
import numpy as np

In [3]:
lista = [0,1,2,3,4]
array_1d=np.array(lista)

In [4]:
type(array_1d)

numpy.ndarray

In [5]:
array_1d

array([0, 1, 2, 3, 4])

In [6]:
lista + 2

TypeError: can only concatenate list (not "int") to list

In [7]:
#A los arrays se pueden hacer operaciones vectorizadas
array_1d + 2

array([2, 3, 4, 5, 6])

In [8]:
array_1d * 5

array([ 0,  5, 10, 15, 20])

In [9]:
array_1d / 5

array([0. , 0.2, 0.4, 0.6, 0.8])

## Arreglos de 2 dimnesiones

In [12]:
list2=[[0,1,2],[3,4,5],[6,7,8]]
list2

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [13]:
arr2d=np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr2_f=np.array(list2, dtype="float") ## convertir el type

In [15]:
# un array no puede tener diferentes tipos de datos como las listas

In [16]:
#crear array y convertir a booleanos : arr2d_b=np.array([1,0,10], ftype="bool")

In [17]:
list2

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [18]:
list2=[[1,2,3,4], [3,4,5,6], [5,6,7,8]]

In [19]:
arr2=np.array(list2,dtype="float")
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [20]:
print("Shapel:",arr2.shape)
print("Data type:",arr2.dtype)
print("size:",arr2.size)
print("numero de dimensiones",arr2.ndim)

Shapel: (3, 4)
Data type: float64
size: 12
numero de dimensiones 2


In [21]:
#Acceder a los elementos del arreglo

In [22]:
#extraer 2 primeras filas y 2 primeras columnas
arr2[:2,:2]

array([[1., 2.],
       [3., 4.]])

In [23]:
#boolean indexing


In [27]:
print("arr2:", arr2)
arr2>4

arr2: [[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
b=arr2>4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
arr2[b]

array([5., 6., 5., 6., 7., 8.])

In [30]:
#Valores faltantes o infinitos (agregar a arr2)
arr2[1,1]=np.nan #no es un número
arr2[1,2]=np.inf #infinito
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [32]:
valores_faltantes_bool=np.isnan(arr2)|np.isinf(arr2)
valores_faltantes_bool

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [33]:
#filtrar utilizando matriz, sustituyendo tru por -1
arr2[valores_faltantes_bool]=-1
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [34]:
#calcular MEDIA, MÍNIMO Y MÁXIMO

In [35]:
print("Media:",arr2.mean())
print("Máximo:",arr2.max())
print("Minimo:",arr2.min())

Media: 3.5833333333333335
Máximo: 8.0
Minimo: -1.0


In [36]:
#Crear arreglo a partir de otro arreglo, ver notas nextia

In [39]:
# Ponemos una semilla de 100 para reproducibilidad, (numeros pseudoaleatorios)
np.random.seed(100)
print(np.random.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [41]:
np.random.seed(100)
arr_rand=np.random.randint(0,10,size=50)
arr_rand

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2, 2, 2, 1, 0, 8, 4, 0, 9, 6, 2, 4, 1,
       5, 3, 4, 4, 3, 7, 1, 1, 7, 7, 0, 2, 9, 9, 3, 2, 5, 8, 1, 0, 7, 6,
       2, 0, 8, 2, 5, 1])

In [42]:
#checar valores únicos
np.unique(arr_rand,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([6, 6, 9, 4, 5, 4, 2, 6, 5, 3], dtype=int64))

In [45]:
vals_unicos,frecuencias = np.unique(arr_rand, return_counts=True)

In [46]:
vals_unicos

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
frecuencias

array([6, 6, 9, 4, 5, 4, 2, 6, 5, 3], dtype=int64)

## Importar y exportar datos de archivos CSV

In [52]:
ruta_url="https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv"
data=np.genfromtxt(ruta_url, delimiter=",",skip_header=1,filling_values=-999,dtype="float")

In [53]:
data[0]

array([ 1.800e+01,  8.000e+00,  3.070e+02,  1.300e+02,  3.504e+03,
        1.200e+01,  7.000e+01,  1.000e+00, -9.990e+02])

In [56]:
np.set_printoptions(suppress=True) #eliminar notación cientifica

In [57]:
data[0]

array([  18.,    8.,  307.,  130., 3504.,   12.,   70.,    1., -999.])

In [58]:
np.savetxt("archivo_nuevo_de_texto_.csv",data, delimiter="|")