## Numpy
### Ejercicios prácticos
### Escribe código Python con Numpy para realizar las siguientes operaciones:
#### 1. Determinar si ninguno de los elementos de un arreglo es cero.

In [1]:
import numpy as np

In [67]:
arr_con_ceros = np.array([1,2,3,4,5,6,0,4,3,2])
arr_sin_ceros = np.array([1,2,3,4,5,6,7,8,9])
list=[[51,2,6],[43,5,46],[7,88,9]]
arr_inf_nan = np.array(list,dtype=float)
arr_inf_nan[1,2]=np.inf
arr_inf_nan[2,1]=np.inf
arr_inf_nan[1,1]=np.nan
list2=[[3,4,6],[4,8,6],[7,8,9]]
arr2=np.array(list2,dtype=float)

print(arr_con_ceros)
print(arr_sin_ceros)
print(arr_inf_nan)
print(arr2)

[1 2 3 4 5 6 0 4 3 2]
[1 2 3 4 5 6 7 8 9]
[[51.  2.  6.]
 [43. nan inf]
 [ 7. inf  9.]]
[[3. 4. 6.]
 [4. 8. 6.]
 [7. 8. 9.]]


In [68]:
print("ninguno de los elementos es cero? en el primer arreglo: ",np.all(arr_con_ceros))
print("ninguno de los elementos es cero? en el segundo arreglo: ", np.all(arr_sin_ceros))

ninguno de los elementos es cero? en el primer arreglo:  False
ninguno de los elementos es cero? en el segundo arreglo:  True


#### 2. Determinar si un arreglo contiene algún elemnto que no sea cero.

#### 3. Analizar un arreglo de numpy y determinar en sus elementos si existen valores que sean infinitos o valores no numéricos (NaN).

In [69]:
valores_nan_inf=np.isnan(arr_inf_nan)|np.isinf(arr_inf_nan)
valores_nan_inf

array([[False, False, False],
       [False,  True,  True],
       [False,  True, False]])

#### 4. Determinar si un arreglo de Numpy contiene valores infinitos.

In [70]:
valores_inf=np.isinf(arr_inf_nan)
print("este es el arreglo con inf y NAN: \n",arr_inf_nan)
print("Hay valores infinitos?:\n",valores_inf)

este es el arreglo con inf y NAN: 
 [[51.  2.  6.]
 [43. nan inf]
 [ 7. inf  9.]]
Hay valores infinitos?:
 [[False False False]
 [False False  True]
 [False  True False]]


#### 5. Analizar un arreglo de Numpy y determinar si hay valores NaN

In [71]:
valores_inf=np.isnan(arr_inf_nan)
print("este es el arreglo con inf y NAN: \n",arr_inf_nan)
print("\n Hay valores nan?:\n",valores_inf)

este es el arreglo con inf y NAN: 
 [[51.  2.  6.]
 [43. nan inf]
 [ 7. inf  9.]]

 Hay valores nan?:
 [[False False False]
 [False  True False]
 [False False False]]


#### 6. Realizar una comparación elemento a elemento de dos arreglos. Contempla mayor, mayor o igual, menor y menor o igual.

In [72]:
print("Arreglo 1\n",arr_inf_nan)
print("\n Arreglo 2 \n",arr2)
print("\n Arreglo 1 mayor que arreglo 2?\n",arr_inf_nan > arr2)

Arreglo 1
 [[51.  2.  6.]
 [43. nan inf]
 [ 7. inf  9.]]

 Arreglo 2 
 [[3. 4. 6.]
 [4. 8. 6.]
 [7. 8. 9.]]

 Arreglo 1 mayor que arreglo 2?
 [[ True False False]
 [ True False  True]
 [False  True False]]


C:\Users\adpli\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in greater
  This is separate from the ipykernel package so we can avoid doing imports until


In [75]:
print("Arreglo 1\n",arr_inf_nan)
print("\n Arreglo 2 \n",arr2)
print("\n Arreglo 1 mayor que arreglo 2?\n",np.greater(arr_inf_nan,arr2))
print("\n Arreglo 1 mayor o igual que arreglo 2?\n",np.greater_equal(arr_inf_nan,arr2))
print("\n Arreglo 1 menor que arreglo 2?\n",np.less(arr_inf_nan,arr2))
print("\n Arreglo 1 mayor o igual que arreglo 2?\n",np.less_equal(arr_inf_nan,arr2))

Arreglo 1
 [[51.  2.  6.]
 [43. nan inf]
 [ 7. inf  9.]]

 Arreglo 2 
 [[3. 4. 6.]
 [4. 8. 6.]
 [7. 8. 9.]]

 Arreglo 1 mayor que arreglo 2?
 [[ True False False]
 [ True False  True]
 [False  True False]]

 Arreglo 1 mayor o igual que arreglo 2?
 [[ True False  True]
 [ True False  True]
 [ True  True  True]]

 Arreglo 1 menor que arreglo 2?
 [[False  True False]
 [False False False]
 [False False False]]

 Arreglo 1 mayor o igual que arreglo 2?
 [[False  True  True]
 [False False False]
 [ True False  True]]


C:\Users\adpli\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in greater
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\adpli\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in greater_equal
  after removing the cwd from sys.path.
C:\Users\adpli\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in less
  """
C:\Users\adpli\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in less_equal
  


#### 7. Crear un arreglo que contenga los valores 1, 7, 13 y 105, y posteriormente determinar la cantidad de memoria que ocupa el arreglo.

In [76]:
arr3=np.array([1,7,13,105])
print(arr3)
print(arr3.nbytes)

[  1   7  13 105]
16


#### 8. Crear un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.

In [82]:
arr0s=np.zeros([10])
arr10s=np.ones([10])
arr5s=np.full((10),5)
print(arr0s)
print(arr10s)
print(arr5s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


#### 9. Crear un arreglo que contenga todos los números enteros entre 30 y 70.

In [90]:
arreglo_enteros=np.arange(30,71,1)
print(arreglo_enteros)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#### 10. Crear un arreglo que contenga los números pares entre 30 y 70

In [91]:
arreglo_pares=np.arange(30,71,2)
print(arreglo_pares)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### 11. Crear una matriz identidad de 3x3

In [93]:
matriz_identidad = np.identity(3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Generar un número aleatorio entre 0 y 1

In [ ]:
num_random = 